/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../common';

export interface KlerosLiquidProxyInterface extends utils.Interface {
  functions: {
    'appealCost(bytes32)': FunctionFragment;
    'appealKlerosArbitratorRuling(bytes32,address,address,uint256,string)': FunctionFragment;
    'appealPeriod(bytes32)': FunctionFragment;
    'arbitrationCost()': FunctionFragment;
    'claimHashToDispute(bytes32)': FunctionFragment;
    'claimHashToDisputeId(bytes32)': FunctionFragment;
    'claimsManager()': FunctionFragment;
    'courts(uint256)': FunctionFragment;
    'createDispute(bytes32,address,address,uint256,string)': FunctionFragment;
    'currentRuling(bytes32)': FunctionFragment;
    'disputeIdToClaimDetails(uint256)': FunctionFragment;
    'disputeStatus(bytes32)': FunctionFragment;
    'executeRuling(bytes32)': FunctionFragment;
    'getSubCourt(uint96)': FunctionFragment;
    'klerosArbitrator()': FunctionFragment;
    'klerosArbitratorExtraData()': FunctionFragment;
    'multicall(bytes[])': FunctionFragment;
    'rule(uint256,uint256)': FunctionFragment;
    'submitEvidenceToKlerosArbitrator(bytes32,string)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'appealCost'
      | 'appealKlerosArbitratorRuling'
      | 'appealPeriod'
      | 'arbitrationCost'
      | 'claimHashToDispute'
      | 'claimHashToDisputeId'
      | 'claimsManager'
      | 'courts'
      | 'createDispute'
      | 'currentRuling'
      | 'disputeIdToClaimDetails'
      | 'disputeStatus'
      | 'executeRuling'
      | 'getSubCourt'
      | 'klerosArbitrator'
      | 'klerosArbitratorExtraData'
      | 'multicall'
      | 'rule'
      | 'submitEvidenceToKlerosArbitrator'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'appealCost', values: [PromiseOrValue<BytesLike>]): string;
  encodeFunctionData(
    functionFragment: 'appealKlerosArbitratorRuling',
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(functionFragment: 'appealPeriod', values: [PromiseOrValue<BytesLike>]): string;
  encodeFunctionData(functionFragment: 'arbitrationCost', values?: undefined): string;
  encodeFunctionData(functionFragment: 'claimHashToDispute', values: [PromiseOrValue<BytesLike>]): string;
  encodeFunctionData(functionFragment: 'claimHashToDisputeId', values: [PromiseOrValue<BytesLike>]): string;
  encodeFunctionData(functionFragment: 'claimsManager', values?: undefined): string;
  encodeFunctionData(functionFragment: 'courts', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: 'createDispute',
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(functionFragment: 'currentRuling', values: [PromiseOrValue<BytesLike>]): string;
  encodeFunctionData(functionFragment: 'disputeIdToClaimDetails', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'disputeStatus', values: [PromiseOrValue<BytesLike>]): string;
  encodeFunctionData(functionFragment: 'executeRuling', values: [PromiseOrValue<BytesLike>]): string;
  encodeFunctionData(functionFragment: 'getSubCourt', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'klerosArbitrator', values?: undefined): string;
  encodeFunctionData(functionFragment: 'klerosArbitratorExtraData', values?: undefined): string;
  encodeFunctionData(functionFragment: 'multicall', values: [PromiseOrValue<BytesLike>[]]): string;
  encodeFunctionData(
    functionFragment: 'rule',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: 'submitEvidenceToKlerosArbitrator',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: 'appealCost', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'appealKlerosArbitratorRuling', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'appealPeriod', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'arbitrationCost', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimHashToDispute', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimHashToDisputeId', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimsManager', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'courts', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createDispute', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'currentRuling', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'disputeIdToClaimDetails', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'disputeStatus', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'executeRuling', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getSubCourt', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'klerosArbitrator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'klerosArbitratorExtraData', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'multicall', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'rule', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'submitEvidenceToKlerosArbitrator', data: BytesLike): Result;

  events: {
    'AppealedKlerosArbitratorRuling(bytes32,address,uint256)': EventFragment;
    'CreatedDispute(bytes32,address,uint256)': EventFragment;
    'Dispute(address,uint256,uint256,uint256)': EventFragment;
    'Evidence(address,uint256,address,string)': EventFragment;
    'MetaEvidence(uint256,string)': EventFragment;
    'Ruling(address,uint256,uint256)': EventFragment;
    'SubmittedEvidenceToKlerosArbitrator(bytes32,address,string)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'AppealedKlerosArbitratorRuling'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'CreatedDispute'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Dispute'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Evidence'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'MetaEvidence'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Ruling'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SubmittedEvidenceToKlerosArbitrator'): EventFragment;
}

export interface AppealedKlerosArbitratorRulingEventObject {
  claimHash: string;
  sender: string;
  disputeId: BigNumber;
}
export type AppealedKlerosArbitratorRulingEvent = TypedEvent<
  [string, string, BigNumber],
  AppealedKlerosArbitratorRulingEventObject
>;

export type AppealedKlerosArbitratorRulingEventFilter = TypedEventFilter<AppealedKlerosArbitratorRulingEvent>;

export interface CreatedDisputeEventObject {
  claimHash: string;
  claimant: string;
  disputeId: BigNumber;
}
export type CreatedDisputeEvent = TypedEvent<[string, string, BigNumber], CreatedDisputeEventObject>;

export type CreatedDisputeEventFilter = TypedEventFilter<CreatedDisputeEvent>;

export interface DisputeEventObject {
  _arbitrator: string;
  _disputeID: BigNumber;
  _metaEvidenceID: BigNumber;
  _evidenceGroupID: BigNumber;
}
export type DisputeEvent = TypedEvent<[string, BigNumber, BigNumber, BigNumber], DisputeEventObject>;

export type DisputeEventFilter = TypedEventFilter<DisputeEvent>;

export interface EvidenceEventObject {
  _arbitrator: string;
  _evidenceGroupID: BigNumber;
  _party: string;
  _evidence: string;
}
export type EvidenceEvent = TypedEvent<[string, BigNumber, string, string], EvidenceEventObject>;

export type EvidenceEventFilter = TypedEventFilter<EvidenceEvent>;

export interface MetaEvidenceEventObject {
  _metaEvidenceID: BigNumber;
  _evidence: string;
}
export type MetaEvidenceEvent = TypedEvent<[BigNumber, string], MetaEvidenceEventObject>;

export type MetaEvidenceEventFilter = TypedEventFilter<MetaEvidenceEvent>;

export interface RulingEventObject {
  _arbitrator: string;
  _disputeID: BigNumber;
  _ruling: BigNumber;
}
export type RulingEvent = TypedEvent<[string, BigNumber, BigNumber], RulingEventObject>;

export type RulingEventFilter = TypedEventFilter<RulingEvent>;

export interface SubmittedEvidenceToKlerosArbitratorEventObject {
  claimHash: string;
  sender: string;
  evidence: string;
}
export type SubmittedEvidenceToKlerosArbitratorEvent = TypedEvent<
  [string, string, string],
  SubmittedEvidenceToKlerosArbitratorEventObject
>;

export type SubmittedEvidenceToKlerosArbitratorEventFilter = TypedEventFilter<SubmittedEvidenceToKlerosArbitratorEvent>;

export interface KlerosLiquidProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: KlerosLiquidProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    appealCost(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<[BigNumber]>;

    appealKlerosArbitratorRuling(
      policyHash: PromiseOrValue<BytesLike>,
      claimant: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      claimAmountInUsd: PromiseOrValue<BigNumberish>,
      evidence: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    appealPeriod(
      claimHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { start: BigNumber; end: BigNumber }>;

    arbitrationCost(overrides?: CallOverrides): Promise<[BigNumber]>;

    claimHashToDispute(
      claimHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, number, BigNumber, BigNumber, BigNumber, boolean] & {
        subCourtId: BigNumber;
        arbitrated: string;
        numberOfChoices: BigNumber;
        period: number;
        lastPeriodChange: BigNumber;
        drawsInRound: BigNumber;
        commitsInRound: BigNumber;
        ruled: boolean;
      }
    >;

    claimHashToDisputeId(arg0: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<[BigNumber]>;

    claimsManager(overrides?: CallOverrides): Promise<[string]>;

    courts(
      subCourtId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
        parent: BigNumber;
        hiddenVotes: boolean;
        minStake: BigNumber;
        alpha: BigNumber;
        feeForJuror: BigNumber;
        jurorsForCourtJump: BigNumber;
      }
    >;

    createDispute(
      policyHash: PromiseOrValue<BytesLike>,
      claimant: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      claimAmountInUsd: PromiseOrValue<BigNumberish>,
      evidence: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentRuling(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<[BigNumber]>;

    disputeIdToClaimDetails(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string] & {
        policyHash: string;
        claimant: string;
        beneficiary: string;
        amountInUsd: BigNumber;
        evidence: string;
      }
    >;

    disputeStatus(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<[number]>;

    executeRuling(
      claimHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getSubCourt(
      subCourtId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], [BigNumber, BigNumber, BigNumber, BigNumber]] & {
        children: BigNumber[];
        timesPerPeriod: [BigNumber, BigNumber, BigNumber, BigNumber];
      }
    >;

    klerosArbitrator(overrides?: CallOverrides): Promise<[string]>;

    klerosArbitratorExtraData(overrides?: CallOverrides): Promise<[string]>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rule(
      disputeId: PromiseOrValue<BigNumberish>,
      ruling: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitEvidenceToKlerosArbitrator(
      claimHash: PromiseOrValue<BytesLike>,
      evidence: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  appealCost(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

  appealKlerosArbitratorRuling(
    policyHash: PromiseOrValue<BytesLike>,
    claimant: PromiseOrValue<string>,
    beneficiary: PromiseOrValue<string>,
    claimAmountInUsd: PromiseOrValue<BigNumberish>,
    evidence: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  appealPeriod(
    claimHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { start: BigNumber; end: BigNumber }>;

  arbitrationCost(overrides?: CallOverrides): Promise<BigNumber>;

  claimHashToDispute(
    claimHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, number, BigNumber, BigNumber, BigNumber, boolean] & {
      subCourtId: BigNumber;
      arbitrated: string;
      numberOfChoices: BigNumber;
      period: number;
      lastPeriodChange: BigNumber;
      drawsInRound: BigNumber;
      commitsInRound: BigNumber;
      ruled: boolean;
    }
  >;

  claimHashToDisputeId(arg0: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

  claimsManager(overrides?: CallOverrides): Promise<string>;

  courts(
    subCourtId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
      parent: BigNumber;
      hiddenVotes: boolean;
      minStake: BigNumber;
      alpha: BigNumber;
      feeForJuror: BigNumber;
      jurorsForCourtJump: BigNumber;
    }
  >;

  createDispute(
    policyHash: PromiseOrValue<BytesLike>,
    claimant: PromiseOrValue<string>,
    beneficiary: PromiseOrValue<string>,
    claimAmountInUsd: PromiseOrValue<BigNumberish>,
    evidence: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentRuling(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

  disputeIdToClaimDetails(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string] & {
      policyHash: string;
      claimant: string;
      beneficiary: string;
      amountInUsd: BigNumber;
      evidence: string;
    }
  >;

  disputeStatus(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<number>;

  executeRuling(
    claimHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getSubCourt(
    subCourtId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], [BigNumber, BigNumber, BigNumber, BigNumber]] & {
      children: BigNumber[];
      timesPerPeriod: [BigNumber, BigNumber, BigNumber, BigNumber];
    }
  >;

  klerosArbitrator(overrides?: CallOverrides): Promise<string>;

  klerosArbitratorExtraData(overrides?: CallOverrides): Promise<string>;

  multicall(
    data: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rule(
    disputeId: PromiseOrValue<BigNumberish>,
    ruling: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitEvidenceToKlerosArbitrator(
    claimHash: PromiseOrValue<BytesLike>,
    evidence: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    appealCost(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    appealKlerosArbitratorRuling(
      policyHash: PromiseOrValue<BytesLike>,
      claimant: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      claimAmountInUsd: PromiseOrValue<BigNumberish>,
      evidence: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    appealPeriod(
      claimHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { start: BigNumber; end: BigNumber }>;

    arbitrationCost(overrides?: CallOverrides): Promise<BigNumber>;

    claimHashToDispute(
      claimHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, number, BigNumber, BigNumber, BigNumber, boolean] & {
        subCourtId: BigNumber;
        arbitrated: string;
        numberOfChoices: BigNumber;
        period: number;
        lastPeriodChange: BigNumber;
        drawsInRound: BigNumber;
        commitsInRound: BigNumber;
        ruled: boolean;
      }
    >;

    claimHashToDisputeId(arg0: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    claimsManager(overrides?: CallOverrides): Promise<string>;

    courts(
      subCourtId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
        parent: BigNumber;
        hiddenVotes: boolean;
        minStake: BigNumber;
        alpha: BigNumber;
        feeForJuror: BigNumber;
        jurorsForCourtJump: BigNumber;
      }
    >;

    createDispute(
      policyHash: PromiseOrValue<BytesLike>,
      claimant: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      claimAmountInUsd: PromiseOrValue<BigNumberish>,
      evidence: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    currentRuling(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    disputeIdToClaimDetails(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string] & {
        policyHash: string;
        claimant: string;
        beneficiary: string;
        amountInUsd: BigNumber;
        evidence: string;
      }
    >;

    disputeStatus(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<number>;

    executeRuling(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<void>;

    getSubCourt(
      subCourtId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], [BigNumber, BigNumber, BigNumber, BigNumber]] & {
        children: BigNumber[];
        timesPerPeriod: [BigNumber, BigNumber, BigNumber, BigNumber];
      }
    >;

    klerosArbitrator(overrides?: CallOverrides): Promise<string>;

    klerosArbitratorExtraData(overrides?: CallOverrides): Promise<string>;

    multicall(data: PromiseOrValue<BytesLike>[], overrides?: CallOverrides): Promise<string[]>;

    rule(
      disputeId: PromiseOrValue<BigNumberish>,
      ruling: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    submitEvidenceToKlerosArbitrator(
      claimHash: PromiseOrValue<BytesLike>,
      evidence: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    'AppealedKlerosArbitratorRuling(bytes32,address,uint256)'(
      claimHash?: PromiseOrValue<BytesLike> | null,
      sender?: PromiseOrValue<string> | null,
      disputeId?: PromiseOrValue<BigNumberish> | null
    ): AppealedKlerosArbitratorRulingEventFilter;
    AppealedKlerosArbitratorRuling(
      claimHash?: PromiseOrValue<BytesLike> | null,
      sender?: PromiseOrValue<string> | null,
      disputeId?: PromiseOrValue<BigNumberish> | null
    ): AppealedKlerosArbitratorRulingEventFilter;

    'CreatedDispute(bytes32,address,uint256)'(
      claimHash?: PromiseOrValue<BytesLike> | null,
      claimant?: PromiseOrValue<string> | null,
      disputeId?: PromiseOrValue<BigNumberish> | null
    ): CreatedDisputeEventFilter;
    CreatedDispute(
      claimHash?: PromiseOrValue<BytesLike> | null,
      claimant?: PromiseOrValue<string> | null,
      disputeId?: PromiseOrValue<BigNumberish> | null
    ): CreatedDisputeEventFilter;

    'Dispute(address,uint256,uint256,uint256)'(
      _arbitrator?: PromiseOrValue<string> | null,
      _disputeID?: PromiseOrValue<BigNumberish> | null,
      _metaEvidenceID?: null,
      _evidenceGroupID?: null
    ): DisputeEventFilter;
    Dispute(
      _arbitrator?: PromiseOrValue<string> | null,
      _disputeID?: PromiseOrValue<BigNumberish> | null,
      _metaEvidenceID?: null,
      _evidenceGroupID?: null
    ): DisputeEventFilter;

    'Evidence(address,uint256,address,string)'(
      _arbitrator?: PromiseOrValue<string> | null,
      _evidenceGroupID?: PromiseOrValue<BigNumberish> | null,
      _party?: PromiseOrValue<string> | null,
      _evidence?: null
    ): EvidenceEventFilter;
    Evidence(
      _arbitrator?: PromiseOrValue<string> | null,
      _evidenceGroupID?: PromiseOrValue<BigNumberish> | null,
      _party?: PromiseOrValue<string> | null,
      _evidence?: null
    ): EvidenceEventFilter;

    'MetaEvidence(uint256,string)'(
      _metaEvidenceID?: PromiseOrValue<BigNumberish> | null,
      _evidence?: null
    ): MetaEvidenceEventFilter;
    MetaEvidence(_metaEvidenceID?: PromiseOrValue<BigNumberish> | null, _evidence?: null): MetaEvidenceEventFilter;

    'Ruling(address,uint256,uint256)'(
      _arbitrator?: PromiseOrValue<string> | null,
      _disputeID?: PromiseOrValue<BigNumberish> | null,
      _ruling?: null
    ): RulingEventFilter;
    Ruling(
      _arbitrator?: PromiseOrValue<string> | null,
      _disputeID?: PromiseOrValue<BigNumberish> | null,
      _ruling?: null
    ): RulingEventFilter;

    'SubmittedEvidenceToKlerosArbitrator(bytes32,address,string)'(
      claimHash?: PromiseOrValue<BytesLike> | null,
      sender?: PromiseOrValue<string> | null,
      evidence?: null
    ): SubmittedEvidenceToKlerosArbitratorEventFilter;
    SubmittedEvidenceToKlerosArbitrator(
      claimHash?: PromiseOrValue<BytesLike> | null,
      sender?: PromiseOrValue<string> | null,
      evidence?: null
    ): SubmittedEvidenceToKlerosArbitratorEventFilter;
  };

  estimateGas: {
    appealCost(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    appealKlerosArbitratorRuling(
      policyHash: PromiseOrValue<BytesLike>,
      claimant: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      claimAmountInUsd: PromiseOrValue<BigNumberish>,
      evidence: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    appealPeriod(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    arbitrationCost(overrides?: CallOverrides): Promise<BigNumber>;

    claimHashToDispute(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    claimHashToDisputeId(arg0: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    claimsManager(overrides?: CallOverrides): Promise<BigNumber>;

    courts(subCourtId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    createDispute(
      policyHash: PromiseOrValue<BytesLike>,
      claimant: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      claimAmountInUsd: PromiseOrValue<BigNumberish>,
      evidence: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentRuling(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    disputeIdToClaimDetails(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    disputeStatus(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<BigNumber>;

    executeRuling(
      claimHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getSubCourt(subCourtId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    klerosArbitrator(overrides?: CallOverrides): Promise<BigNumber>;

    klerosArbitratorExtraData(overrides?: CallOverrides): Promise<BigNumber>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rule(
      disputeId: PromiseOrValue<BigNumberish>,
      ruling: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitEvidenceToKlerosArbitrator(
      claimHash: PromiseOrValue<BytesLike>,
      evidence: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    appealCost(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    appealKlerosArbitratorRuling(
      policyHash: PromiseOrValue<BytesLike>,
      claimant: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      claimAmountInUsd: PromiseOrValue<BigNumberish>,
      evidence: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    appealPeriod(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    arbitrationCost(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimHashToDispute(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimHashToDisputeId(arg0: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimsManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    courts(subCourtId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createDispute(
      policyHash: PromiseOrValue<BytesLike>,
      claimant: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      claimAmountInUsd: PromiseOrValue<BigNumberish>,
      evidence: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentRuling(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    disputeIdToClaimDetails(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    disputeStatus(claimHash: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeRuling(
      claimHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getSubCourt(subCourtId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    klerosArbitrator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    klerosArbitratorExtraData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rule(
      disputeId: PromiseOrValue<BigNumberish>,
      ruling: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitEvidenceToKlerosArbitrator(
      claimHash: PromiseOrValue<BytesLike>,
      evidence: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
