allowBuilds:
  '@parcel/watcher': false
  '@percy/core': false
  core-js: false
  core-js-pure: false
  cypress: false
  keccak: false
  less: false

blockExoticSubdeps: true

minimumReleaseAge: 20160
minimumReleaseAgeExclude:
  - '@api3/commons@1.3.0'

nodeLinker: hoisted

overrides:
  '@typescript-eslint/eslint-plugin': '^6.21.0'
  '@typescript-eslint/parser': '^6.21.0'
  '@types/jest': '^27.5.2'
  '@types/react': '^18.3.31'
  jest-regex-util: '^27.5.1'
  jest-watcher: '^27.5.1'
  jest-worker: '^27.5.1'
